import type { IdentityRole } from "./types.js";

export interface AuthPrincipal {
  accountId: string;
  role: IdentityRole;
  sessionId: string;
}

export const Permissions = [
  "IAM_MANAGE_ACCOUNTS",
  "IAM_READ_AUDIT",
  "DATA_GOVERNANCE_MANAGE",
  "PROVIDER_REVIEW",
  "PROVIDER_SELF_ONBOARD",
  "PROVIDER_MANAGE_SERVICES",
  "PROVIDER_MANAGE_AVAILABILITY",
  "PROVIDER_READ_FINANCIALS",
  "PROVIDER_REFUND_PAYMENTS",
  "PROVIDER_MANAGE_CLAIMS",
  "PATIENT_MANAGE_CONSENT",
  "PATIENT_BOOK_APPOINTMENT",
  "PATIENT_MANAGE_APPOINTMENT",
  "PATIENT_MANAGE_BILLING",
  "PATIENT_MANAGE_INSURANCE",
  "PATIENT_READ_CLAIMS",
  "PATIENT_READ_CLINICAL_RECORD",
  "PATIENT_READ_CLINICAL_ORDERS",
  "PATIENT_READ_CLINICAL_DOCUMENTS",
  "PATIENT_WRITE_CLINICAL_DOCUMENTS",
  "PATIENT_SECURE_MESSAGE",
  "PATIENT_TRANSPORT_REQUEST",
  "PROVIDER_SECURE_MESSAGE",
  "CARE_COORDINATION_MANAGE",
  "SELF_NOTIFICATION_MANAGE",
  "NOTIFICATION_OPERATE",
  "APPOINTMENT_OPERATE",
  "CLINICAL_RECORD_READ",
  "CLINICAL_RECORD_WRITE",
  "CLINICAL_ORDER_READ",
  "CLINICAL_ORDER_WRITE",
  "CLINICAL_DOCUMENT_READ",
  "CLINICAL_DOCUMENT_WRITE",
  "DIAGNOSTIC_REPORT_WRITE",
  "LAB_RESULT_ENTER",
  "LAB_RESULT_VALIDATE",
  "INSURANCE_CHECK",
  "INSURANCE_OPERATE",
  "FINANCE_OPERATE",
  "REVENUE_CYCLE_OPERATE",
  "TELEHEALTH_JOIN",
  "TELEHEALTH_OPERATE",
  "CATALOG_MANAGE",
  "EMERGENCY_REQUEST",
  "EMERGENCY_DISPATCH_OPERATE",
  "EMERGENCY_RESPOND",
  "TRANSPORT_OPERATE",
  "TRANSPORT_RESPOND",
  "SELF_SESSION_MANAGE",
] as const;

export type Permission = (typeof Permissions)[number];

const grants: Record<IdentityRole, readonly Permission[]> = {
  ADMIN: [
    "IAM_MANAGE_ACCOUNTS",
    "IAM_READ_AUDIT",
    "DATA_GOVERNANCE_MANAGE",
    "PROVIDER_REVIEW",
    "SELF_NOTIFICATION_MANAGE",
    "NOTIFICATION_OPERATE",
    "APPOINTMENT_OPERATE",
    "INSURANCE_OPERATE",
    "FINANCE_OPERATE",
    "REVENUE_CYCLE_OPERATE",
    "CATALOG_MANAGE",
    "EMERGENCY_DISPATCH_OPERATE",
    "TRANSPORT_OPERATE",
    "SELF_SESSION_MANAGE",
  ],
  SUPPORT: ["SELF_NOTIFICATION_MANAGE", "SELF_SESSION_MANAGE"],
  PATIENT: [
    "PATIENT_MANAGE_CONSENT",
    "PATIENT_BOOK_APPOINTMENT",
    "PATIENT_MANAGE_APPOINTMENT",
    "PATIENT_MANAGE_BILLING",
    "PATIENT_MANAGE_INSURANCE",
    "PATIENT_READ_CLAIMS",
    "PATIENT_READ_CLINICAL_RECORD",
    "PATIENT_READ_CLINICAL_ORDERS",
    "PATIENT_READ_CLINICAL_DOCUMENTS",
    "PATIENT_WRITE_CLINICAL_DOCUMENTS",
    "PATIENT_SECURE_MESSAGE",
    "PATIENT_TRANSPORT_REQUEST",
    "SELF_NOTIFICATION_MANAGE",
    "INSURANCE_CHECK",
    "TELEHEALTH_JOIN",
    "EMERGENCY_REQUEST",
    "SELF_SESSION_MANAGE",
  ],
  DOCTOR: [
    "PROVIDER_SELF_ONBOARD",
    "PROVIDER_MANAGE_SERVICES",
    "PROVIDER_MANAGE_AVAILABILITY",
    "PROVIDER_READ_FINANCIALS",
    "PROVIDER_REFUND_PAYMENTS",
    "PROVIDER_MANAGE_CLAIMS",
    "PROVIDER_SECURE_MESSAGE",
    "CARE_COORDINATION_MANAGE",
    "SELF_NOTIFICATION_MANAGE",
    "CLINICAL_RECORD_READ",
    "CLINICAL_RECORD_WRITE",
    "CLINICAL_ORDER_READ",
    "CLINICAL_ORDER_WRITE",
    "CLINICAL_DOCUMENT_READ",
    "CLINICAL_DOCUMENT_WRITE",
    "DIAGNOSTIC_REPORT_WRITE",
    "LAB_RESULT_ENTER",
    "LAB_RESULT_VALIDATE",
    "INSURANCE_CHECK",
    "INSURANCE_OPERATE",
    "TELEHEALTH_JOIN",
    "TELEHEALTH_OPERATE",
    "SELF_SESSION_MANAGE",
  ],
  OTHER_PROVIDER: [
    "PROVIDER_SELF_ONBOARD",
    "PROVIDER_MANAGE_SERVICES",
    "PROVIDER_MANAGE_AVAILABILITY",
    "PROVIDER_READ_FINANCIALS",
    "PROVIDER_REFUND_PAYMENTS",
    "PROVIDER_MANAGE_CLAIMS",
    "PROVIDER_SECURE_MESSAGE",
    "CARE_COORDINATION_MANAGE",
    "SELF_NOTIFICATION_MANAGE",
    "CLINICAL_RECORD_READ",
    "CLINICAL_RECORD_WRITE",
    "CLINICAL_ORDER_READ",
    "CLINICAL_ORDER_WRITE",
    "CLINICAL_DOCUMENT_READ",
    "CLINICAL_DOCUMENT_WRITE",
    "DIAGNOSTIC_REPORT_WRITE",
    "LAB_RESULT_ENTER",
    "LAB_RESULT_VALIDATE",
    "INSURANCE_CHECK",
    "INSURANCE_OPERATE",
    "TELEHEALTH_JOIN",
    "TELEHEALTH_OPERATE",
    "EMERGENCY_RESPOND",
    "TRANSPORT_RESPOND",
    "SELF_SESSION_MANAGE",
  ],
};

export function roleHasPermission(role: IdentityRole, permission: Permission): boolean {
  return grants[role].includes(permission);
}

export function principalHasAnyPermission(principal: AuthPrincipal, permissions: readonly Permission[]): boolean {
  return permissions.length === 0 || permissions.some((permission) => roleHasPermission(principal.role, permission));
}

export function canActOnAccount(principal: AuthPrincipal, targetAccountId: string): boolean {
  return principal.accountId === targetAccountId || roleHasPermission(principal.role, "IAM_MANAGE_ACCOUNTS");
}

export function canOwnOnboarding(principal: AuthPrincipal, ownerAccountId: string): boolean {
  return principal.accountId === ownerAccountId && roleHasPermission(principal.role, "PROVIDER_SELF_ONBOARD");
}
