import 'carepoint_localization.dart';
const availabilityLabels = <String, Map<String, String>>{
  'centre': {'en':'Availability centre','es':'Centro de disponibilidad','fr':'Centre de disponibilités','ar':'مركز المواعيد المتاحة'},
  'requests': {'en':'My requests','es':'Mis solicitudes','fr':'Mes demandes','ar':'طلباتي'},
  'notices': {'en':'Availability notices','es':'Avisos de disponibilidad','fr':'Avis de disponibilité','ar':'إشعارات المواعيد المتاحة'},
  'join': {'en':'Request availability','es':'Solicitar disponibilidad','fr':'Demander une disponibilité','ar':'طلب موعد متاح'},
  'consent': {'en':'I agree to in-app availability notices for this request. No appointment or payment is made.','es':'Acepto avisos de disponibilidad en la aplicación para esta solicitud. No se reserva ni se cobra nada.','fr':'J’accepte les avis dans l’application pour cette demande. Aucune réservation ni facturation.','ar':'أوافق على إشعارات المواعيد المتاحة داخل التطبيق لهذا الطلب. لا يتم حجز موعد أو تحصيل أي مبلغ.'},
  'policy': {'en':'No existing appointment is needed. Maximum 20 active requests, each covering at most 62 days.','es':'No necesitas tener una cita. Máximo 20 solicitudes activas, cada una con un intervalo máximo de 62 días.','fr':'Aucun rendez-vous existant nécessaire. Maximum 20 demandes actives de 62 jours chacune.','ar':'لا تحتاج إلى موعد سابق. الحد الأقصى 20 طلباً نشطاً، ولمدة 62 يوماً لكل طلب.'},
  'onDemand': {'en':'Your request can be checked automatically and whenever you select Check availability. In-app alerts are observations, not reservations. This request does not enable SMS, email or push availability alerts.','es':'Tu solicitud puede comprobarse automáticamente y al pulsar Comprobar disponibilidad. Los avisos en la app son observaciones, no reservas. Esta solicitud no activa avisos de disponibilidad por SMS, correo ni push.','fr':'Votre demande peut être vérifiée automatiquement et lorsque vous sélectionnez Vérifier les disponibilités. Les avis dans l’application sont des observations, pas des réservations. Cette demande n’active pas les alertes SMS, e-mail ou push.','ar':'يمكن التحقق من طلبك تلقائياً وعند الضغط على التحقق من المواعيد. تنبيهات التطبيق تعرض نتيجة رصد ولا تمثل حجزاً. هذا الطلب لا يفعّل تنبيهات التوفر عبر الرسائل النصية أو البريد أو الإشعارات الفورية.'},
  'newAlerts': {'en':'new availability alerts','es':'nuevos avisos','fr':'nouveaux avis','ar':'تنبيهات توفر جديدة'},
  'openedFromAlert': {'en':'Opened from an availability alert. Current times must be rechecked before booking.','es':'Abierto desde un aviso de disponibilidad. Los horarios actuales se vuelven a comprobar antes de reservar.','fr':'Ouvert depuis un avis de disponibilité. Les créneaux actuels sont revérifiés avant la réservation.','ar':'تم الفتح من تنبيه توفر. تتم إعادة التحقق من المواعيد الحالية قبل الحجز.'},
  'showAll': {'en':'Show all availability requests','es':'Mostrar todas las solicitudes','fr':'Afficher toutes les demandes','ar':'عرض جميع طلبات المواعيد'},
  'alertOlder': {'en':'This alert may refer to a closed or older request. Review My requests for its current status.','es':'Este aviso puede corresponder a una solicitud cerrada o anterior. Revisa Mis solicitudes para ver su estado actual.','fr':'Cet avis peut concerner une demande fermée ou plus ancienne. Consultez Mes demandes pour son état actuel.','ar':'قد يشير هذا التنبيه إلى طلب مغلق أو أقدم. راجع طلباتي لمعرفة حالته الحالية.'},
  'from': {'en':'From (dd/mm/yyyy)','es':'Desde (dd/mm/yyyy)','fr':'Du (jj/mm/aaaa)','ar':'من (يوم/شهر/سنة)'},
  'to': {'en':'Through (dd/mm/yyyy)','es':'Hasta inclusive (dd/mm/yyyy)','fr':'Au inclus (jj/mm/aaaa)','ar':'حتى شاملاً (يوم/شهر/سنة)'},
  'invalid': {'en':'Choose valid future dates and accept in-app notices.','es':'Elige fechas futuras válidas y acepta los avisos en la aplicación.','fr':'Choisissez des dates futures valides et acceptez les avis.','ar':'اختر تواريخ مستقبلية صحيحة ووافق على الإشعارات.'},
  'saved': {'en':'Request saved. No appointment has been booked.','es':'Solicitud guardada. No se ha reservado ninguna cita.','fr':'Demande enregistrée. Aucun rendez-vous réservé.','ar':'تم حفظ الطلب. لم يتم حجز أي موعد.'},
  'uncertain': {'en':'The request may have been saved. Retry the same request or check My requests.','es':'La solicitud puede haberse guardado. Reintenta la misma solicitud o consulta Mis solicitudes.','fr':'La demande a peut-être été enregistrée. Réessayez ou consultez Mes demandes.','ar':'ربما تم حفظ الطلب. أعد محاولة الطلب نفسه أو تحقق من طلباتي.'},
  'check': {'en':'Check availability','es':'Comprobar disponibilidad','fr':'Vérifier les disponibilités','ar':'التحقق من المواعيد'},
  'view': {'en':'Review available times','es':'Revisar horarios disponibles','fr':'Consulter les créneaux','ar':'مراجعة المواعيد المتاحة'},
  'checked': {'en':'Last checked','es':'Última comprobación','fr':'Dernière vérification','ar':'آخر تحقق'},
  'available': {'en':'Matching times observed','es':'Horarios coincidentes observados','fr':'Créneaux correspondants observés','ar':'المواعيد المطابقة المتاحة'},
  'unread': {'en':'Unread','es':'Sin leer','fr':'Non lu','ar':'غير مقروء'},
  'read': {'en':'Read','es':'Leído','fr':'Lu','ar':'مقروء'},
  'markRead': {'en':'Mark as read','es':'Marcar como leído','fr':'Marquer comme lu','ar':'تحديد كمقروء'},
  'withdraw': {'en':'Withdraw request','es':'Retirar solicitud','fr':'Retirer la demande','ar':'سحب الطلب'},
  'withdrawDetail': {'en':'Stop tracking this request. This does not cancel any appointment.','es':'Dejar de consultar esta solicitud. No se cancela ninguna cita.','fr':'Arrêter le suivi. Aucun rendez-vous n’est annulé.','ar':'إيقاف متابعة هذا الطلب. لا يتم إلغاء أي موعد.'},
  'none': {'en':'No matching times now. Your request remains active.','es':'No hay horarios coincidentes ahora. Tu solicitud sigue activa.','fr':'Aucun créneau correspondant. Votre demande reste active.','ar':'لا توجد مواعيد مطابقة حالياً. يظل طلبك نشطاً.'},
  'limited': {'en':'First 100 matching times shown. Narrow the requested date range to see other dates.','es':'Se muestran los primeros 100 horarios. Reduce el intervalo solicitado para consultar otras fechas.','fr':'Les 100 premiers créneaux sont affichés. Réduisez la période pour consulter d’autres dates.','ar':'يتم عرض أول 100 موعد مطابق. ضيّق الفترة المطلوبة للاطلاع على تواريخ أخرى.'},
  'WAITING': {'en':'Waiting','es':'En espera','fr':'En attente','ar':'قيد الانتظار'},
  'WITHDRAWN': {'en':'Withdrawn','es':'Retirada','fr':'Retirée','ar':'مسحوب'},
  'EXPIRED': {'en':'Expired','es':'Caducada','fr':'Expirée','ar':'منتهي الصلاحية'},
  'FULFILLED': {'en':'Appointment booked','es':'Cita reservada','fr':'Rendez-vous réservé','ar':'تم حجز الموعد'},
};
String availabilityText(CarePointLocale locale, String key) => availabilityLabels[key]?[locale.name] ?? availabilityLabels[key]?['en'] ?? key;
