import 'package:flutter/widgets.dart';

enum CarePointLocale { en, ar, fr, es }

extension CarePointLocaleInfo on CarePointLocale {
  Locale get locale => Locale(name);
  TextDirection get textDirection => this == CarePointLocale.ar ? TextDirection.rtl : TextDirection.ltr;
  String get label => switch (this) {
    CarePointLocale.en => 'English',
    CarePointLocale.ar => 'العربية',
    CarePointLocale.fr => 'Français',
    CarePointLocale.es => 'Español',
  };
}

const Map<CarePointLocale, Map<String, String>> messages = {
  CarePointLocale.en: {
    'auth.liveApi': 'Connected to the CarePoint live API', 'auth.email': 'Email', 'auth.password': 'Password', 'auth.signIn': 'Sign in', 'auth.mfaPrompt': 'Enter the 6-digit code from your authenticator.', 'auth.mfaCode': 'MFA code', 'auth.verify': 'Verify', 'auth.api': 'API', 'auth.signOut': 'Sign out',
    'common.retry': 'Retry', 'common.refresh': 'Refresh', 'common.cancel': 'Cancel', 'common.save': 'Save', 'common.loading': 'Loading…', 'common.none': 'Nothing to show yet', 'common.error': 'Something went wrong',
    'patient.greeting': 'Good morning', 'patient.prompt': 'Find and book verified care', 'patient.emergency': 'EMERGENCY AMBULANCE', 'patient.emergencyAction': 'Request urgent help', 'patient.emergencyHint': 'Priority flow · separate from ordinary booking', 'patient.book': 'Book visit', 'patient.telemedicine': 'Telemedicine', 'patient.homeCare': 'Home care', 'patient.findCare': 'Find care', 'patient.emergencyTitle': 'Emergency ambulance', 'patient.emergencyText': 'Emergency ambulance remains a dedicated dispatch flow and is not handled by ordinary appointment booking.', 'patient.requestNow': 'Open emergency flow', 'patient.cancel': 'Cancel', 'patient.search': 'Search care', 'patient.searchHint': 'Doctor, provider or service', 'patient.allModalities': 'All modalities', 'patient.results': 'Available services', 'patient.slots': 'Available times', 'patient.myVisits': 'My appointments', 'patient.bookNow': 'Book this time', 'patient.booked': 'Appointment confirmed', 'patient.cancelVisit': 'Cancel appointment', 'patient.noSlots': 'No available times in the next 30 days.', 'patient.noVisits': 'No appointments yet.', 'patient.price': 'Price',
    'doctor.title': 'Doctor · Today', 'doctor.boundary': 'ALL SPECIALTIES · ONE DOCTOR DOMAIN', 'doctor.queue': 'Clinical queue',
    'provider.title': 'CarePoint Provider', 'provider.boundary': 'NON-DOCTOR PROVIDER DOMAIN', 'provider.route': 'Service route', 'provider.nextJob': 'NEXT FIELD JOB', 'provider.nursing': 'Home nursing visit', 'provider.startRoute': 'Start route', 'provider.note': 'This application serves all non-doctor healthcare and medical transport categories. Doctors use the separate Doctor application.',
    'workspace.agenda': 'Agenda', 'workspace.services': 'Services', 'workspace.availability': 'Availability', 'workspace.noAppointments': 'No appointments in this period.', 'workspace.noServices': 'Create your first bookable service.', 'workspace.noRules': 'No availability rules yet.', 'workspace.newService': 'New service', 'workspace.serviceName': 'Service name', 'workspace.modality': 'Modality', 'workspace.duration': 'Duration (minutes)', 'workspace.priceMinor': 'Price (minor units)', 'workspace.currency': 'Currency', 'workspace.newRule': 'New availability rule', 'workspace.timezone': 'IANA timezone', 'workspace.weekday': 'Weekday', 'workspace.startTime': 'Start HH:MM', 'workspace.endTime': 'End HH:MM', 'workspace.interval': 'Interval (minutes)', 'workspace.generate': 'Generate next 30 days', 'workspace.generated': 'Availability generated', 'workspace.activeOnly': 'Only approved active providers can manage scheduling.'
  },
  CarePointLocale.ar: {
    'auth.liveApi': 'متصل بواجهة CarePoint الفعلية', 'auth.email': 'البريد الإلكتروني', 'auth.password': 'كلمة المرور', 'auth.signIn': 'تسجيل الدخول', 'auth.mfaPrompt': 'أدخل الرمز المكون من 6 أرقام من تطبيق المصادقة.', 'auth.mfaCode': 'رمز التحقق', 'auth.verify': 'تحقق', 'auth.api': 'واجهة API', 'auth.signOut': 'تسجيل الخروج',
    'common.retry': 'إعادة المحاولة', 'common.refresh': 'تحديث', 'common.cancel': 'إلغاء', 'common.save': 'حفظ', 'common.loading': 'جارٍ التحميل…', 'common.none': 'لا توجد بيانات بعد', 'common.error': 'حدث خطأ',
    'patient.greeting': 'صباح الخير', 'patient.prompt': 'ابحث عن رعاية موثوقة واحجزها', 'patient.emergency': 'إسعاف طارئ', 'patient.emergencyAction': 'اطلب مساعدة عاجلة', 'patient.emergencyHint': 'مسار أولوية · منفصل عن الحجز العادي', 'patient.book': 'احجز زيارة', 'patient.telemedicine': 'طب عن بُعد', 'patient.homeCare': 'رعاية منزلية', 'patient.findCare': 'ابحث عن رعاية', 'patient.emergencyTitle': 'إسعاف طارئ', 'patient.emergencyText': 'يبقى الإسعاف الطارئ مسار إرسال مستقل ولا تتم معالجته ضمن الحجز العادي.', 'patient.requestNow': 'فتح مسار الطوارئ', 'patient.cancel': 'إلغاء', 'patient.search': 'البحث عن رعاية', 'patient.searchHint': 'طبيب أو مقدم خدمة أو خدمة', 'patient.allModalities': 'كل الأنماط', 'patient.results': 'الخدمات المتاحة', 'patient.slots': 'الأوقات المتاحة', 'patient.myVisits': 'مواعيدي', 'patient.bookNow': 'احجز هذا الوقت', 'patient.booked': 'تم تأكيد الموعد', 'patient.cancelVisit': 'إلغاء الموعد', 'patient.noSlots': 'لا توجد أوقات متاحة خلال 30 يومًا القادمة.', 'patient.noVisits': 'لا توجد مواعيد بعد.', 'patient.price': 'السعر',
    'doctor.title': 'الطبيب · اليوم', 'doctor.boundary': 'كل التخصصات · نطاق أطباء واحد', 'doctor.queue': 'قائمة الحالات السريرية',
    'provider.title': 'مقدم خدمة CarePoint', 'provider.boundary': 'نطاق مقدمي الرعاية غير الأطباء', 'provider.route': 'مسار الخدمة', 'provider.nextJob': 'المهمة الميدانية التالية', 'provider.nursing': 'زيارة تمريض منزلية', 'provider.startRoute': 'ابدأ المسار', 'provider.note': 'هذا التطبيق يخدم جميع فئات الرعاية الصحية غير الأطباء والنقل الطبي. يستخدم الأطباء تطبيق الأطباء المنفصل.',
    'workspace.agenda': 'الجدول', 'workspace.services': 'الخدمات', 'workspace.availability': 'التوفر', 'workspace.noAppointments': 'لا توجد مواعيد في هذه الفترة.', 'workspace.noServices': 'أنشئ أول خدمة قابلة للحجز.', 'workspace.noRules': 'لا توجد قواعد توفر بعد.', 'workspace.newService': 'خدمة جديدة', 'workspace.serviceName': 'اسم الخدمة', 'workspace.modality': 'النمط', 'workspace.duration': 'المدة بالدقائق', 'workspace.priceMinor': 'السعر بالوحدة الصغرى', 'workspace.currency': 'العملة', 'workspace.newRule': 'قاعدة توفر جديدة', 'workspace.timezone': 'المنطقة الزمنية IANA', 'workspace.weekday': 'يوم الأسبوع', 'workspace.startTime': 'البداية HH:MM', 'workspace.endTime': 'النهاية HH:MM', 'workspace.interval': 'الفاصل بالدقائق', 'workspace.generate': 'إنشاء 30 يومًا القادمة', 'workspace.generated': 'تم إنشاء أوقات التوفر', 'workspace.activeOnly': 'يمكن فقط لمقدمي الخدمة المعتمدين والنشطين إدارة الجدولة.'
  },
  CarePointLocale.fr: {
    'auth.liveApi': 'Connecté à l’API CarePoint réelle', 'auth.email': 'E-mail', 'auth.password': 'Mot de passe', 'auth.signIn': 'Se connecter', 'auth.mfaPrompt': 'Saisissez le code à 6 chiffres de votre authentificateur.', 'auth.mfaCode': 'Code MFA', 'auth.verify': 'Vérifier', 'auth.api': 'API', 'auth.signOut': 'Se déconnecter',
    'common.retry': 'Réessayer', 'common.refresh': 'Actualiser', 'common.cancel': 'Annuler', 'common.save': 'Enregistrer', 'common.loading': 'Chargement…', 'common.none': 'Aucune donnée pour le moment', 'common.error': 'Une erreur est survenue',
    'patient.greeting': 'Bonjour', 'patient.prompt': 'Trouvez et réservez des soins vérifiés', 'patient.emergency': 'AMBULANCE D’URGENCE', 'patient.emergencyAction': 'Demander une aide urgente', 'patient.emergencyHint': 'Flux prioritaire · séparé des réservations', 'patient.book': 'Prendre rendez-vous', 'patient.telemedicine': 'Télémédecine', 'patient.homeCare': 'Soins à domicile', 'patient.findCare': 'Trouver des soins', 'patient.emergencyTitle': 'Ambulance d’urgence', 'patient.emergencyText': 'L’ambulance d’urgence reste un flux de dispatch séparé des rendez-vous ordinaires.', 'patient.requestNow': 'Ouvrir le flux d’urgence', 'patient.cancel': 'Annuler', 'patient.search': 'Rechercher des soins', 'patient.searchHint': 'Médecin, prestataire ou service', 'patient.allModalities': 'Toutes les modalités', 'patient.results': 'Services disponibles', 'patient.slots': 'Créneaux disponibles', 'patient.myVisits': 'Mes rendez-vous', 'patient.bookNow': 'Réserver ce créneau', 'patient.booked': 'Rendez-vous confirmé', 'patient.cancelVisit': 'Annuler le rendez-vous', 'patient.noSlots': 'Aucun créneau disponible dans les 30 prochains jours.', 'patient.noVisits': 'Aucun rendez-vous.', 'patient.price': 'Prix',
    'doctor.title': 'Médecin · Aujourd’hui', 'doctor.boundary': 'TOUTES SPÉCIALITÉS · UN DOMAINE MÉDECIN', 'doctor.queue': 'File clinique',
    'provider.title': 'Prestataire CarePoint', 'provider.boundary': 'DOMAINE PRESTATAIRES NON MÉDECINS', 'provider.route': 'Itinéraire de service', 'provider.nextJob': 'PROCHAINE MISSION TERRAIN', 'provider.nursing': 'Visite infirmière à domicile', 'provider.startRoute': 'Démarrer l’itinéraire', 'provider.note': 'Cette application couvre toutes les catégories de santé non médecins et de transport médical. Les médecins utilisent l’application Médecin séparée.',
    'workspace.agenda': 'Agenda', 'workspace.services': 'Services', 'workspace.availability': 'Disponibilité', 'workspace.noAppointments': 'Aucun rendez-vous sur cette période.', 'workspace.noServices': 'Créez votre premier service réservable.', 'workspace.noRules': 'Aucune règle de disponibilité.', 'workspace.newService': 'Nouveau service', 'workspace.serviceName': 'Nom du service', 'workspace.modality': 'Modalité', 'workspace.duration': 'Durée (minutes)', 'workspace.priceMinor': 'Prix (unités mineures)', 'workspace.currency': 'Devise', 'workspace.newRule': 'Nouvelle règle de disponibilité', 'workspace.timezone': 'Fuseau IANA', 'workspace.weekday': 'Jour de la semaine', 'workspace.startTime': 'Début HH:MM', 'workspace.endTime': 'Fin HH:MM', 'workspace.interval': 'Intervalle (minutes)', 'workspace.generate': 'Générer les 30 prochains jours', 'workspace.generated': 'Disponibilité générée', 'workspace.activeOnly': 'Seuls les prestataires approuvés et actifs peuvent gérer la planification.'
  },
  CarePointLocale.es: {
    'auth.liveApi': 'Conectado a la API real de CarePoint', 'auth.email': 'Correo electrónico', 'auth.password': 'Contraseña', 'auth.signIn': 'Iniciar sesión', 'auth.mfaPrompt': 'Introduce el código de 6 dígitos de tu autenticador.', 'auth.mfaCode': 'Código MFA', 'auth.verify': 'Verificar', 'auth.api': 'API', 'auth.signOut': 'Cerrar sesión',
    'common.retry': 'Reintentar', 'common.refresh': 'Actualizar', 'common.cancel': 'Cancelar', 'common.save': 'Guardar', 'common.loading': 'Cargando…', 'common.none': 'Todavía no hay datos', 'common.error': 'Se ha producido un error',
    'patient.greeting': 'Buenos días', 'patient.prompt': 'Busca y reserva atención verificada', 'patient.emergency': 'AMBULANCIA DE URGENCIAS', 'patient.emergencyAction': 'Solicitar ayuda urgente', 'patient.emergencyHint': 'Flujo prioritario · separado de la reserva ordinaria', 'patient.book': 'Reservar visita', 'patient.telemedicine': 'Telemedicina', 'patient.homeCare': 'Atención domiciliaria', 'patient.findCare': 'Buscar atención', 'patient.emergencyTitle': 'Ambulancia de urgencias', 'patient.emergencyText': 'La ambulancia de urgencias sigue siendo un flujo de despacho independiente y no forma parte de las reservas ordinarias.', 'patient.requestNow': 'Abrir flujo de urgencias', 'patient.cancel': 'Cancelar', 'patient.search': 'Buscar atención', 'patient.searchHint': 'Médico, proveedor o servicio', 'patient.allModalities': 'Todas las modalidades', 'patient.results': 'Servicios disponibles', 'patient.slots': 'Horarios disponibles', 'patient.myVisits': 'Mis citas', 'patient.bookNow': 'Reservar este horario', 'patient.booked': 'Cita confirmada', 'patient.cancelVisit': 'Cancelar cita', 'patient.noSlots': 'No hay horarios disponibles en los próximos 30 días.', 'patient.noVisits': 'Todavía no hay citas.', 'patient.price': 'Precio',
    'doctor.title': 'Médico · Hoy', 'doctor.boundary': 'TODAS LAS ESPECIALIDADES · UN DOMINIO MÉDICO', 'doctor.queue': 'Cola clínica',
    'provider.title': 'Proveedor CarePoint', 'provider.boundary': 'DOMINIO DE PROVEEDORES NO MÉDICOS', 'provider.route': 'Ruta de servicio', 'provider.nextJob': 'PRÓXIMO TRABAJO DE CAMPO', 'provider.nursing': 'Visita de enfermería a domicilio', 'provider.startRoute': 'Iniciar ruta', 'provider.note': 'Esta aplicación sirve a todas las categorías sanitarias no médicas y de transporte médico. Los médicos utilizan la aplicación Médicos separada.',
    'workspace.agenda': 'Agenda', 'workspace.services': 'Servicios', 'workspace.availability': 'Disponibilidad', 'workspace.noAppointments': 'No hay citas en este periodo.', 'workspace.noServices': 'Crea tu primer servicio reservable.', 'workspace.noRules': 'Todavía no hay reglas de disponibilidad.', 'workspace.newService': 'Nuevo servicio', 'workspace.serviceName': 'Nombre del servicio', 'workspace.modality': 'Modalidad', 'workspace.duration': 'Duración (minutos)', 'workspace.priceMinor': 'Precio (unidades menores)', 'workspace.currency': 'Moneda', 'workspace.newRule': 'Nueva regla de disponibilidad', 'workspace.timezone': 'Zona horaria IANA', 'workspace.weekday': 'Día de la semana', 'workspace.startTime': 'Inicio HH:MM', 'workspace.endTime': 'Fin HH:MM', 'workspace.interval': 'Intervalo (minutos)', 'workspace.generate': 'Generar próximos 30 días', 'workspace.generated': 'Disponibilidad generada', 'workspace.activeOnly': 'Solo los proveedores aprobados y activos pueden gestionar la agenda.'
  },
};

String cpText(CarePointLocale locale, String key) => messages[locale]?[key] ?? messages[CarePointLocale.en]?[key] ?? key;
