import 'carepoint_localization.dart';

String financeText(CarePointLocale locale, String key) =>
    _financeStrings[locale.name]?[key] ?? _financeStrings['en']?[key] ?? key;

const _financeStrings = <String, Map<String, String>>{
  'en': {
    'finance': 'Finance',
    'billing': 'Billing',
    'insurance': 'Insurance',
    'invoices': 'Invoices',
    'receipts': 'Receipts',
    'noInvoices': 'No invoices yet.',
    'noReceipts': 'No receipts yet.',
    'noCoverage': 'No insurance coverage has been added.',
    'noLedger': 'No financial activity yet.',
    'total': 'Total',
    'balance': 'Balance due',
    'paid': 'Paid',
    'refunded': 'Refunded',
    'patientShare': 'Patient responsibility',
    'insurerShare': 'Insurer responsibility',
    'payNow': 'Pay securely',
    'checkPayment': 'Check payment status',
    'paymentSettled': 'Payment completed.',
    'paymentPending': 'Payment is still pending.',
    'openSecurePayment': 'Continue in secure payment page',
    'hostedNotice': 'Payment details are entered only on the payment provider page. CarePoint does not request or store card number or CVV.',
    'invalidHostedUrl': 'The payment provider returned an invalid secure URL.',
    'coverages': 'Coverage',
    'addCoverage': 'Add coverage',
    'payerCode': 'Payer code',
    'payerName': 'Payer name',
    'policyReference': 'Policy/member reference',
    'policyHelp': 'This reference is stored server-side and is not shown again in normal coverage views.',
    'displayLabel': 'Plan label',
    'effectiveFrom': 'Effective from (YYYY-MM-DD)',
    'effectiveUntil': 'Effective until (YYYY-MM-DD)',
    'deactivate': 'Deactivate',
    'eligibility': 'Eligibility',
    'checkEligibility': 'Check eligibility',
    'selectAppointment': 'Select appointment',
    'selectCoverage': 'Select coverage',
    'eligible': 'Eligible',
    'priorAuthorization': 'Prior authorization',
    'requestPriorAuthorization': 'Request prior authorization',
    'financialSummary': 'Financial summary',
    'availableBalance': 'Available balance',
    'ledger': 'Ledger',
    'appointmentFinance': 'Appointment finance',
    'refund': 'Refund',
    'refundCharge': 'Refund charge',
    'amountMinor': 'Amount in minor units',
    'reason': 'Reason',
    'status': 'Status',
    'reference': 'Reference',
    'refresh': 'Refresh',
    'activity': 'Insurance activity',
    'save': 'Save',
    'cancel': 'Cancel',
    'close': 'Close',
    'provider': 'Provider',
    'service': 'Service',
    'appointment': 'Appointment',
    'noEligibleAppointment': 'No appointment is available for this operation.',
    'refundSubmitted': 'Refund completed.',
    'priorAuthSubmitted': 'Prior authorization request submitted.',
  },
  'ar': {
    'finance': 'المالية',
    'billing': 'الفوترة',
    'insurance': 'التأمين',
    'invoices': 'الفواتير',
    'receipts': 'الإيصالات',
    'noInvoices': 'لا توجد فواتير بعد.',
    'noReceipts': 'لا توجد إيصالات بعد.',
    'noCoverage': 'لم تتم إضافة تغطية تأمينية بعد.',
    'noLedger': 'لا توجد حركة مالية بعد.',
    'total': 'الإجمالي',
    'balance': 'الرصيد المستحق',
    'paid': 'المدفوع',
    'refunded': 'المسترد',
    'patientShare': 'حصة المريض',
    'insurerShare': 'حصة شركة التأمين',
    'payNow': 'دفع آمن',
    'checkPayment': 'التحقق من حالة الدفع',
    'paymentSettled': 'تم الدفع بنجاح.',
    'paymentPending': 'عملية الدفع ما زالت معلقة.',
    'openSecurePayment': 'المتابعة إلى صفحة الدفع الآمنة',
    'hostedNotice': 'تُدخل بيانات الدفع فقط في صفحة مزود الدفع. لا يطلب CarePoint رقم البطاقة أو CVV ولا يخزنهما.',
    'invalidHostedUrl': 'أعاد مزود الدفع رابطاً آمناً غير صالح.',
    'coverages': 'التغطية',
    'addCoverage': 'إضافة تغطية',
    'payerCode': 'رمز شركة التأمين',
    'payerName': 'اسم شركة التأمين',
    'policyReference': 'مرجع الوثيقة/العضوية',
    'policyHelp': 'يُحفظ هذا المرجع على الخادم ولا يظهر مجدداً في العرض العادي للتغطية.',
    'displayLabel': 'اسم الخطة',
    'effectiveFrom': 'سارية من (YYYY-MM-DD)',
    'effectiveUntil': 'سارية حتى (YYYY-MM-DD)',
    'deactivate': 'إلغاء التفعيل',
    'eligibility': 'الأهلية التأمينية',
    'checkEligibility': 'التحقق من الأهلية',
    'selectAppointment': 'اختيار الموعد',
    'selectCoverage': 'اختيار التغطية',
    'eligible': 'مؤهل',
    'priorAuthorization': 'الموافقة المسبقة',
    'requestPriorAuthorization': 'طلب موافقة مسبقة',
    'financialSummary': 'الملخص المالي',
    'availableBalance': 'الرصيد المتاح',
    'ledger': 'السجل المالي',
    'appointmentFinance': 'مالية الموعد',
    'refund': 'استرداد',
    'refundCharge': 'استرداد دفعة',
    'amountMinor': 'المبلغ بالوحدة الصغرى',
    'reason': 'السبب',
    'status': 'الحالة',
    'reference': 'المرجع',
    'refresh': 'تحديث',
    'activity': 'نشاط التأمين',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'close': 'إغلاق',
    'provider': 'مقدم الخدمة',
    'service': 'الخدمة',
    'appointment': 'الموعد',
    'noEligibleAppointment': 'لا يوجد موعد متاح لهذه العملية.',
    'refundSubmitted': 'تم الاسترداد.',
    'priorAuthSubmitted': 'تم إرسال طلب الموافقة المسبقة.',
  },
  'fr': {
    'finance': 'Finances',
    'billing': 'Facturation',
    'insurance': 'Assurance',
    'invoices': 'Factures',
    'receipts': 'Reçus',
    'noInvoices': 'Aucune facture pour le moment.',
    'noReceipts': 'Aucun reçu pour le moment.',
    'noCoverage': 'Aucune couverture d’assurance ajoutée.',
    'noLedger': 'Aucune activité financière pour le moment.',
    'total': 'Total',
    'balance': 'Solde dû',
    'paid': 'Payé',
    'refunded': 'Remboursé',
    'patientShare': 'Part patient',
    'insurerShare': 'Part assureur',
    'payNow': 'Payer en sécurité',
    'checkPayment': 'Vérifier le paiement',
    'paymentSettled': 'Paiement terminé.',
    'paymentPending': 'Le paiement est encore en attente.',
    'openSecurePayment': 'Continuer vers le paiement sécurisé',
    'hostedNotice': 'Les données de paiement sont saisies uniquement sur la page du prestataire de paiement. CarePoint ne demande ni ne stocke le numéro de carte ou le CVV.',
    'invalidHostedUrl': 'Le prestataire de paiement a renvoyé une URL sécurisée non valide.',
    'coverages': 'Couverture',
    'addCoverage': 'Ajouter une couverture',
    'payerCode': 'Code assureur',
    'payerName': 'Nom de l’assureur',
    'policyReference': 'Référence police/adhérent',
    'policyHelp': 'Cette référence est conservée côté serveur et n’est pas réaffichée dans les vues normales.',
    'displayLabel': 'Libellé du plan',
    'effectiveFrom': 'Valable à partir du (YYYY-MM-DD)',
    'effectiveUntil': 'Valable jusqu’au (YYYY-MM-DD)',
    'deactivate': 'Désactiver',
    'eligibility': 'Éligibilité',
    'checkEligibility': 'Vérifier l’éligibilité',
    'selectAppointment': 'Sélectionner un rendez-vous',
    'selectCoverage': 'Sélectionner une couverture',
    'eligible': 'Éligible',
    'priorAuthorization': 'Autorisation préalable',
    'requestPriorAuthorization': 'Demander une autorisation préalable',
    'financialSummary': 'Résumé financier',
    'availableBalance': 'Solde disponible',
    'ledger': 'Grand livre',
    'appointmentFinance': 'Finances du rendez-vous',
    'refund': 'Remboursement',
    'refundCharge': 'Rembourser le paiement',
    'amountMinor': 'Montant en unité mineure',
    'reason': 'Motif',
    'status': 'Statut',
    'reference': 'Référence',
    'refresh': 'Actualiser',
    'activity': 'Activité assurance',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'close': 'Fermer',
    'provider': 'Prestataire',
    'service': 'Service',
    'appointment': 'Rendez-vous',
    'noEligibleAppointment': 'Aucun rendez-vous n’est disponible pour cette opération.',
    'refundSubmitted': 'Remboursement effectué.',
    'priorAuthSubmitted': 'Demande d’autorisation préalable envoyée.',
  },
  'es': {
    'finance': 'Finanzas',
    'billing': 'Facturación',
    'insurance': 'Seguro',
    'invoices': 'Facturas',
    'receipts': 'Recibos',
    'noInvoices': 'Todavía no hay facturas.',
    'noReceipts': 'Todavía no hay recibos.',
    'noCoverage': 'Todavía no se ha añadido cobertura de seguro.',
    'noLedger': 'Todavía no hay actividad financiera.',
    'total': 'Total',
    'balance': 'Saldo pendiente',
    'paid': 'Pagado',
    'refunded': 'Reembolsado',
    'patientShare': 'Responsabilidad del paciente',
    'insurerShare': 'Responsabilidad de la aseguradora',
    'payNow': 'Pagar de forma segura',
    'checkPayment': 'Comprobar estado del pago',
    'paymentSettled': 'Pago completado.',
    'paymentPending': 'El pago todavía está pendiente.',
    'openSecurePayment': 'Continuar a la página de pago segura',
    'hostedNotice': 'Los datos de pago se introducen únicamente en la página del proveedor de pagos. CarePoint no solicita ni almacena número de tarjeta ni CVV.',
    'invalidHostedUrl': 'El proveedor de pagos devolvió una URL segura no válida.',
    'coverages': 'Cobertura',
    'addCoverage': 'Añadir cobertura',
    'payerCode': 'Código de aseguradora',
    'payerName': 'Nombre de aseguradora',
    'policyReference': 'Referencia de póliza/miembro',
    'policyHelp': 'Esta referencia se guarda en el servidor y no vuelve a mostrarse en las vistas normales de cobertura.',
    'displayLabel': 'Nombre del plan',
    'effectiveFrom': 'Válido desde (YYYY-MM-DD)',
    'effectiveUntil': 'Válido hasta (YYYY-MM-DD)',
    'deactivate': 'Desactivar',
    'eligibility': 'Elegibilidad',
    'checkEligibility': 'Comprobar elegibilidad',
    'selectAppointment': 'Seleccionar cita',
    'selectCoverage': 'Seleccionar cobertura',
    'eligible': 'Elegible',
    'priorAuthorization': 'Autorización previa',
    'requestPriorAuthorization': 'Solicitar autorización previa',
    'financialSummary': 'Resumen financiero',
    'availableBalance': 'Saldo disponible',
    'ledger': 'Libro mayor',
    'appointmentFinance': 'Finanzas de la cita',
    'refund': 'Reembolso',
    'refundCharge': 'Reembolsar cobro',
    'amountMinor': 'Importe en unidad menor',
    'reason': 'Motivo',
    'status': 'Estado',
    'reference': 'Referencia',
    'refresh': 'Actualizar',
    'activity': 'Actividad del seguro',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'close': 'Cerrar',
    'provider': 'Proveedor',
    'service': 'Servicio',
    'appointment': 'Cita',
    'noEligibleAppointment': 'No hay ninguna cita disponible para esta operación.',
    'refundSubmitted': 'Reembolso completado.',
    'priorAuthSubmitted': 'Solicitud de autorización previa enviada.',
  },
};
