import 'carepoint_localization.dart';

String revenueText(CarePointLocale locale, String key) =>
    _strings[locale.name]?[key] ?? _strings['en']?[key] ?? key;

const _strings = <String, Map<String, String>>{
  'en': {
    'title': 'Claims & EOB',
    'claims': 'Insurance claims',
    'eob': 'Explanation of benefits',
    'remittances': 'Remittances',
    'noClaims': 'No insurance claims yet.',
    'noEob': 'No explanation of benefits yet.',
    'version': 'Version',
    'submittedAmount': 'Submitted amount',
    'allowed': 'Allowed amount',
    'insurerPaid': 'Insurer payment',
    'patientResponsibility': 'Patient responsibility',
    'adjustment': 'Adjustment',
    'reconciliation': 'Reconciliation',
    'denial': 'Denial',
    'submitClaim': 'Submit claim',
    'refreshClaim': 'Refresh claim',
    'reworkClaim': 'Correct and resubmit',
    'reasonCode': 'Correction reason code',
    'claimSubmitted': 'Claim submitted.',
    'claimReworked': 'Corrected claim submitted.',
    'selectAppointment': 'Select completed appointment',
    'missingCoverage': 'A valid eligible insurance coverage is required before claim submission.',
    'reviewRequired': 'Financial review required',
    'refresh': 'Refresh',
    'cancel': 'Cancel',
    'continue': 'Continue',
    'finance': 'Finance',
  },
  'ar': {
    'title': 'المطالبات وشرح المزايا',
    'claims': 'مطالبات التأمين',
    'eob': 'شرح المزايا',
    'remittances': 'تحويلات شركة التأمين',
    'noClaims': 'لا توجد مطالبات تأمين بعد.',
    'noEob': 'لا يوجد شرح مزايا بعد.',
    'version': 'الإصدار',
    'submittedAmount': 'المبلغ المطالب به',
    'allowed': 'المبلغ المسموح',
    'insurerPaid': 'دفعة شركة التأمين',
    'patientResponsibility': 'مسؤولية المريض',
    'adjustment': 'التسوية',
    'reconciliation': 'المطابقة المالية',
    'denial': 'سبب الرفض',
    'submitClaim': 'إرسال مطالبة',
    'refreshClaim': 'تحديث المطالبة',
    'reworkClaim': 'تصحيح وإعادة الإرسال',
    'reasonCode': 'رمز سبب التصحيح',
    'claimSubmitted': 'تم إرسال المطالبة.',
    'claimReworked': 'تم إرسال المطالبة المصححة.',
    'selectAppointment': 'اختيار موعد مكتمل',
    'missingCoverage': 'يلزم وجود تغطية تأمينية مؤهلة قبل إرسال المطالبة.',
    'reviewRequired': 'يلزم مراجعة مالية',
    'refresh': 'تحديث',
    'cancel': 'إلغاء',
    'continue': 'متابعة',
    'finance': 'المالية',
  },
  'fr': {
    'title': 'Demandes & EOB',
    'claims': 'Demandes de remboursement',
    'eob': 'Explication des prestations',
    'remittances': 'Règlements assureur',
    'noClaims': 'Aucune demande pour le moment.',
    'noEob': 'Aucune explication des prestations pour le moment.',
    'version': 'Version',
    'submittedAmount': 'Montant soumis',
    'allowed': 'Montant autorisé',
    'insurerPaid': 'Paiement assureur',
    'patientResponsibility': 'Part patient',
    'adjustment': 'Ajustement',
    'reconciliation': 'Rapprochement',
    'denial': 'Refus',
    'submitClaim': 'Soumettre une demande',
    'refreshClaim': 'Actualiser la demande',
    'reworkClaim': 'Corriger et resoumettre',
    'reasonCode': 'Code du motif de correction',
    'claimSubmitted': 'Demande soumise.',
    'claimReworked': 'Demande corrigée soumise.',
    'selectAppointment': 'Sélectionner un rendez-vous terminé',
    'missingCoverage': 'Une couverture d’assurance éligible est requise avant la soumission.',
    'reviewRequired': 'Révision financière requise',
    'refresh': 'Actualiser',
    'cancel': 'Annuler',
    'continue': 'Continuer',
    'finance': 'Finances',
  },
  'es': {
    'title': 'Reclamaciones y EOB',
    'claims': 'Reclamaciones al seguro',
    'eob': 'Explicación de beneficios',
    'remittances': 'Remesas de la aseguradora',
    'noClaims': 'Todavía no hay reclamaciones.',
    'noEob': 'Todavía no hay explicación de beneficios.',
    'version': 'Versión',
    'submittedAmount': 'Importe reclamado',
    'allowed': 'Importe autorizado',
    'insurerPaid': 'Pago de la aseguradora',
    'patientResponsibility': 'Responsabilidad del paciente',
    'adjustment': 'Ajuste',
    'reconciliation': 'Conciliación',
    'denial': 'Denegación',
    'submitClaim': 'Enviar reclamación',
    'refreshClaim': 'Actualizar reclamación',
    'reworkClaim': 'Corregir y reenviar',
    'reasonCode': 'Código del motivo de corrección',
    'claimSubmitted': 'Reclamación enviada.',
    'claimReworked': 'Reclamación corregida enviada.',
    'selectAppointment': 'Seleccionar cita completada',
    'missingCoverage': 'Se requiere una cobertura de seguro elegible antes de enviar la reclamación.',
    'reviewRequired': 'Se requiere revisión financiera',
    'refresh': 'Actualizar',
    'cancel': 'Cancelar',
    'continue': 'Continuar',
    'finance': 'Finanzas',
  },
};
