"use client";

import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { useI18n, type Locale } from "@/lib/i18n";
import styles from "@/components/B6GovernanceCenter.module.css";

type HubCard = readonly [id: string, title: string, description: string, href: string];

const cards={
 en:[["ADM-084","Clinical terminology","Versioned coding systems and concepts.","/clinical-terminology"],["ADM-088","Patient data quality","Reproducible findings and governed remediation.","/data-quality/patients"],["ADM-090","Controlled patient merge","Preview conflicts before identity merge.","/data-quality/merge"],["ADM-100","Notification templates","PHI-safe EN/AR/FR/ES multichannel text.","/notification-templates"],["ADM-101","Feature governance","Backend-enforced rollout policies.","/features"],["ADM-110","Localization","Versioned dynamic EN/AR/FR/ES content.","/localization"],["ADM-089","Duplicate patients","Deterministic candidates for human review.","/data-quality/duplicates"],["ADM-102","Integration Center","Connector health without exposing secrets.","/integrations"],["ADM-111","Audit exports","Encrypted compliance exports with SHA-256 evidence.","/audit/exports"],["ADM-112","Clinical operations","Continuity KPIs and authorized drill-down.","/clinical-operations"]],
 ar:[["ADM-084","المصطلحات السريرية","أنظمة ترميز ومفاهيم ذات إصدارات.","/clinical-terminology"],["ADM-088","جودة بيانات المرضى","نتائج قابلة للتكرار ومعالجة محكومة.","/data-quality/patients"],["ADM-090","دمج المرضى","معاينة التعارضات قبل دمج الهوية.","/data-quality/merge"],["ADM-100","قوالب الإشعارات","نص آمن متعدد القنوات بأربع لغات.","/notification-templates"],["ADM-101","حوكمة الميزات","سياسات إطلاق يفرضها الخادم.","/features"],["ADM-110","الترجمة","محتوى ديناميكي بإصدارات بأربع لغات.","/localization"],["ADM-089","المرضى المكررون","مرشحون حتميون للمراجعة البشرية.","/data-quality/duplicates"],["ADM-102","مركز التكامل","حالة الموصلات دون كشف الأسرار.","/integrations"],["ADM-111","تصدير التدقيق","تصدير امتثال مشفر مع دليل SHA-256.","/audit/exports"],["ADM-112","العمليات السريرية","مؤشرات استمرارية مع تفاصيل محكومة.","/clinical-operations"]],
 fr:[["ADM-084","Terminologie clinique","Systèmes et concepts de codage versionnés.","/clinical-terminology"],["ADM-088","Qualité des données","Constats reproductibles et remédiation gouvernée.","/data-quality/patients"],["ADM-090","Fusion patient contrôlée","Prévisualisation des conflits avant fusion.","/data-quality/merge"],["ADM-100","Modèles de notification","Texte multicanal sans PHI en quatre langues.","/notification-templates"],["ADM-101","Gouvernance des features","Politiques de rollout imposées par le backend.","/features"],["ADM-110","Localisation","Contenu dynamique versionné EN/AR/FR/ES.","/localization"],["ADM-089","Patients en doublon","Candidats déterministes pour revue humaine.","/data-quality/duplicates"],["ADM-102","Centre d’intégration","Santé des connecteurs sans exposer les secrets.","/integrations"],["ADM-111","Exports d’audit","Exports chiffrés avec preuve SHA-256.","/audit/exports"],["ADM-112","Opérations cliniques","KPI de continuité et drill-down autorisé.","/clinical-operations"]],
 es:[["ADM-084","Terminología clínica","Sistemas de códigos y conceptos versionados.","/clinical-terminology"],["ADM-088","Calidad de datos","Hallazgos reproducibles y remediación gobernada.","/data-quality/patients"],["ADM-090","Fusión controlada","Previsualización de conflictos antes de fusionar.","/data-quality/merge"],["ADM-100","Plantillas de notificación","Texto multicanal sin PHI en cuatro idiomas.","/notification-templates"],["ADM-101","Gobernanza de features","Políticas de rollout impuestas también por backend.","/features"],["ADM-110","Localización","Contenido dinámico versionado EN/AR/FR/ES.","/localization"],["ADM-089","Pacientes duplicados","Candidatos deterministas para revisión humana.","/data-quality/duplicates"],["ADM-102","Integration Center","Salud de conectores sin exponer secretos.","/integrations"],["ADM-111","Exportaciones de auditoría","Exportaciones cifradas con evidencia SHA-256.","/audit/exports"],["ADM-112","Operaciones clínicas","KPIs de continuidad y drill-down autorizado.","/clinical-operations"]],
} satisfies Record<Locale,readonly HubCard[]>;

export default function GovernancePage(){const {locale}=useI18n();return <AppShell active="12" eyebrow="V2 · B6" title="Governance Center"><div className={styles.hub}>{cards[locale].map(([id,title,description,href])=><Link key={id} href={href}><small>{id}</small><strong>{title}</strong><span>{description}</span></Link>)}</div></AppShell>;}
