name: carepoint_patient
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carepoint_mobile_core:
    path: ../../packages/mobile_core
  geolocator: ^14.0.2

flutter:
  uses-material-design: true
