"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export const supportedLocales = ["en", "ar", "fr", "es"] as const;
export type Locale = (typeof supportedLocales)[number];
export type Direction = "ltr" | "rtl";

const localeLabels: Record<Locale, string> = { en: "English", ar: "العربية", fr: "Français", es: "Español" };

const messages = {
  en: {
    "common.today":"Today","common.open":"Open","common.filter":"Filter","common.verified":"Verified","common.review":"Review","common.independentEntity":"Independent entity","common.secureSession":"SECURE SESSION","common.exportSnapshot":"Export snapshot","common.live":"LIVE",
    "shell.clinicalOperations":"Clinical Operations","shell.globalCommand":"Global command...","shell.systemModules":"SYSTEM MODULES","shell.e2eeStatus":"E2EE STATUS","shell.shieldPolicy":"Shield policy active","shell.globalCareNetwork":"Global Care Network","shell.platformAdministrator":"Platform Administrator",
    "nav.commandCenter":"Command Center","nav.otherProviders":"Other Providers","nav.doctors":"Doctors & Specialties","nav.appointments":"Appointments","nav.patientWorkspaces":"Patient Workspaces","nav.telehealth":"Telehealth Hub","nav.analytics":"Analytics & SLA","nav.security":"Security & E2EE",
    "command.eyebrow":"REAL-TIME PLATFORM","command.title":"Operations Command Center","command.heroOverline":"CAREPOINT NEXT","command.heroTitle":"Clinical network in command.","command.heroText":"One operational view across independent doctors, non-doctor providers, medical transport and patient demand.","command.platformHealth":"PLATFORM HEALTH","command.nominal":"Nominal","command.platformDetail":"API 99.99% · DB healthy · Queue normal","command.visitsToday":"Visits today","command.activeDoctors":"Active doctors","command.otherProviders":"Other providers","command.urgentRequests":"Urgent requests","command.allSpecialties":"All specialties","command.doctorsExcluded":"Doctors explicitly excluded","command.ambulanceQueue":"Ambulance priority queue","command.liveDemand":"LIVE DEMAND","command.visitsByModality":"Visits by modality","command.clinicVisits":"Clinic visits","command.telemedicine":"Telemedicine","command.homeVisits":"Home visits","command.emergencyAmbulance":"Emergency ambulance","command.confirmed74":"74% confirmed","command.joining12":"12 joining now","command.enRoute9":"9 en route","command.dispatching2":"2 dispatching","command.priorityDispatch":"Priority dispatch","command.requestReceived":"Patient request received","command.requestDetail":"Beirut · GPS verified · dispatching eligible ambulance","command.elapsed":"elapsed","command.openDispatch":"Open dispatch","command.callPatient":"Call patient","command.boundaryHealth":"BOUNDARY HEALTH","command.providerDomains":"Provider domains","command.doctorDomain":"DOCTOR DOMAIN","command.doctorBoundary":"All doctors · all specialties","command.doctorBoundaryText":"Dedicated application, credentialing and specialty hierarchy.","command.otherDomain":"OTHER PROVIDER DOMAIN","command.otherBoundary":"Healthcare + ground/air transport","command.otherBoundaryText":"Flexible taxonomy. Doctors can never be classified here.","command.patientDomain":"PATIENT DOMAIN","command.patientBoundary":"One global patient identity","command.patientBoundaryText":"Consent controls provider access to sensitive clinical context.",
    "providers.eyebrow":"FLEXIBLE TAXONOMY · DOCTORS EXCLUDED","providers.title":"Independent Other Providers","providers.domainRule":"DOMAIN RULE","providers.ruleTitle":"Every non-doctor provider is independent.","providers.ruleText":"Healthcare branches, emergency ambulance, ground transport and air medical transport are managed here. Doctors are always managed in the dedicated Doctor domain.","providers.newCategory":"+ New category","providers.search":"Search providers, categories or coverage...","providers.allStatus":"All status","providers.allFamilies":"All families","providers.provider":"Provider","providers.category":"Category","providers.status":"Status","providers.mode":"Mode / availability","providers.coverage":"Coverage","providers.nonDoctorHealthcare":"NON-DOCTOR HEALTHCARE","providers.nonDoctorHealthcareText":"Nursing, ATS, physiotherapy, nutrition and future allied health categories.","providers.groundTransport":"GROUND MEDICAL TRANSPORT","providers.groundTransportText":"Scheduled or specialized patient transport by ground.","providers.airTransport":"AIR MEDICAL TRANSPORT","providers.airTransportText":"Medical aviation services with additional credential requirements.","providers.emergencyAmbulance":"EMERGENCY AMBULANCE","providers.emergencyAmbulanceText":"Urgent providers eligible for priority dispatch from Patient Home.","providers.configureSchema":"Configure schema →",
    "doctors.eyebrow":"DEDICATED DOCTOR DOMAIN","doctors.title":"Doctors & Medical Specialties","doctors.allBranches":"ALL MEDICAL BRANCHES","doctors.heroTitle":"One doctor application. Every specialty.","doctors.heroText":"Every physician belongs to this domain, from general medicine to highly specialized surgical and diagnostic disciplines. No doctor belongs to Other Providers.","doctors.activeDoctors":"active doctors","doctors.credentialReady":"94% credential ready","doctors.credentialGovernance":"CREDENTIAL GOVERNANCE","doctors.activationReadiness":"Doctor activation readiness","doctors.licenseVerified":"Medical license verified","doctors.specialtyAssigned":"Primary specialty assigned","doctors.mfaEnrolled":"MFA enrolled",
    "appointments.eyebrow":"MULTI-MODAL OPERATIONS","appointments.title":"Unified Appointment Operations","appointments.clinic":"Clinic","appointments.telemedicine":"Telemedicine","appointments.homeVisit":"Home visit","appointments.emergency":"Emergency Ambulance","appointments.todayCount":"{count} today","appointments.separateFlow":"Separate urgent flow","appointments.timeline":"Care delivery timeline"
  },
  ar: {
    "common.today":"اليوم","common.open":"فتح","common.filter":"تصفية","common.verified":"موثّق","common.review":"قيد المراجعة","common.independentEntity":"كيان مستقل","common.secureSession":"جلسة آمنة","common.exportSnapshot":"تصدير لقطة","common.live":"مباشر",
    "shell.clinicalOperations":"العمليات السريرية","shell.globalCommand":"أمر عام...","shell.systemModules":"وحدات النظام","shell.e2eeStatus":"حالة التشفير الطرفي","shell.shieldPolicy":"سياسة الحماية مفعّلة","shell.globalCareNetwork":"شبكة الرعاية العالمية","shell.platformAdministrator":"مسؤول المنصة",
    "nav.commandCenter":"مركز القيادة","nav.otherProviders":"مقدمو الرعاية الآخرون","nav.doctors":"الأطباء والتخصصات","nav.appointments":"المواعيد","nav.patientWorkspaces":"مساحات المرضى","nav.telehealth":"مركز الطب عن بُعد","nav.analytics":"التحليلات وSLA","nav.security":"الأمان والتشفير",
    "command.eyebrow":"منصة آنية","command.title":"مركز قيادة العمليات","command.heroOverline":"CAREPOINT NEXT","command.heroTitle":"الشبكة السريرية تحت السيطرة.","command.heroText":"رؤية تشغيلية موحدة للأطباء المستقلين ومقدمي الرعاية غير الأطباء والنقل الطبي وطلب المرضى.","command.platformHealth":"صحة المنصة","command.nominal":"طبيعي","command.platformDetail":"API 99.99% · قاعدة البيانات سليمة · الطابور طبيعي","command.visitsToday":"زيارات اليوم","command.activeDoctors":"الأطباء النشطون","command.otherProviders":"مقدمو الرعاية الآخرون","command.urgentRequests":"طلبات عاجلة","command.allSpecialties":"جميع التخصصات","command.doctorsExcluded":"الأطباء مستثنون صراحةً","command.ambulanceQueue":"طابور أولوية الإسعاف","command.liveDemand":"الطلب المباشر","command.visitsByModality":"الزيارات حسب النمط","command.clinicVisits":"زيارات العيادة","command.telemedicine":"الطب عن بُعد","command.homeVisits":"زيارات منزلية","command.emergencyAmbulance":"إسعاف طارئ","command.confirmed74":"74% مؤكدة","command.joining12":"12 ينضمون الآن","command.enRoute9":"9 في الطريق","command.dispatching2":"2 قيد الإرسال","command.priorityDispatch":"إرسال بأولوية","command.requestReceived":"تم استلام طلب المريض","command.requestDetail":"بيروت · GPS موثّق · إرسال سيارة إسعاف مؤهلة","command.elapsed":"منقضٍ","command.openDispatch":"فتح الإرسال","command.callPatient":"الاتصال بالمريض","command.boundaryHealth":"سلامة الحدود","command.providerDomains":"نطاقات مقدمي الخدمة","command.doctorDomain":"نطاق الأطباء","command.doctorBoundary":"كل الأطباء · كل التخصصات","command.doctorBoundaryText":"تطبيق مخصص واعتمادات وتسلسل للتخصصات.","command.otherDomain":"نطاق مقدمي الرعاية الآخرين","command.otherBoundary":"رعاية صحية + نقل بري/جوي","command.otherBoundaryText":"تصنيف مرن. لا يمكن تصنيف الأطباء هنا.","command.patientDomain":"نطاق المريض","command.patientBoundary":"هوية مريض عالمية واحدة","command.patientBoundaryText":"الموافقة تتحكم بوصول مقدمي الرعاية للسياق السريري الحساس.",
    "providers.eyebrow":"تصنيف مرن · الأطباء مستثنون","providers.title":"مقدمو الرعاية الآخرون المستقلون","providers.domainRule":"قاعدة النطاق","providers.ruleTitle":"كل مقدم رعاية غير طبيب هو كيان مستقل.","providers.ruleText":"تدار هنا فروع الرعاية الصحية والإسعاف الطارئ والنقل الطبي البري والجوي. تتم إدارة الأطباء دائماً في نطاق الأطباء المخصص.","providers.newCategory":"+ فئة جديدة","providers.search":"ابحث عن مقدم أو فئة أو تغطية...","providers.allStatus":"كل الحالات","providers.allFamilies":"كل العائلات","providers.provider":"مقدم الخدمة","providers.category":"الفئة","providers.status":"الحالة","providers.mode":"النمط / التوفر","providers.coverage":"التغطية","providers.nonDoctorHealthcare":"رعاية صحية غير طبية","providers.nonDoctorHealthcareText":"تمريض وATS وعلاج طبيعي وتغذية وفئات صحية مساندة مستقبلية.","providers.groundTransport":"نقل طبي بري","providers.groundTransportText":"نقل مرضى مجدول أو متخصص براً.","providers.airTransport":"نقل طبي جوي","providers.airTransportText":"خدمات طيران طبي مع متطلبات اعتماد إضافية.","providers.emergencyAmbulance":"إسعاف طارئ","providers.emergencyAmbulanceText":"مقدمو إسعاف مؤهلون للإرسال ذي الأولوية من الصفحة الرئيسية للمريض.","providers.configureSchema":"تهيئة المخطط ←",
    "doctors.eyebrow":"نطاق أطباء مخصص","doctors.title":"الأطباء والتخصصات الطبية","doctors.allBranches":"جميع الفروع الطبية","doctors.heroTitle":"تطبيق أطباء واحد. كل التخصصات.","doctors.heroText":"كل طبيب ينتمي إلى هذا النطاق، من الطب العام إلى أدق التخصصات الجراحية والتشخيصية. لا ينتمي أي طبيب إلى مقدمي الرعاية الآخرين.","doctors.activeDoctors":"أطباء نشطون","doctors.credentialReady":"94% جاهزية الاعتماد","doctors.credentialGovernance":"حوكمة الاعتمادات","doctors.activationReadiness":"جاهزية تفعيل الأطباء","doctors.licenseVerified":"الرخصة الطبية موثقة","doctors.specialtyAssigned":"التخصص الأساسي محدد","doctors.mfaEnrolled":"MFA مفعّل",
    "appointments.eyebrow":"عمليات متعددة الأنماط","appointments.title":"عمليات المواعيد الموحدة","appointments.clinic":"عيادة","appointments.telemedicine":"طب عن بُعد","appointments.homeVisit":"زيارة منزلية","appointments.emergency":"إسعاف طارئ","appointments.todayCount":"{count} اليوم","appointments.separateFlow":"مسار طارئ منفصل","appointments.timeline":"الجدول الزمني لتقديم الرعاية"
  },
  fr: {
    "common.today":"Aujourd’hui","common.open":"Ouvrir","common.filter":"Filtrer","common.verified":"Vérifié","common.review":"En révision","common.independentEntity":"Entité indépendante","common.secureSession":"SESSION SÉCURISÉE","common.exportSnapshot":"Exporter l’instantané","common.live":"LIVE",
    "shell.clinicalOperations":"Opérations cliniques","shell.globalCommand":"Commande globale...","shell.systemModules":"MODULES DU SYSTÈME","shell.e2eeStatus":"STATUT E2EE","shell.shieldPolicy":"Politique de protection active","shell.globalCareNetwork":"Réseau mondial de soins","shell.platformAdministrator":"Administrateur de la plateforme",
    "nav.commandCenter":"Centre de commande","nav.otherProviders":"Autres prestataires","nav.doctors":"Médecins et spécialités","nav.appointments":"Rendez-vous","nav.patientWorkspaces":"Espaces patients","nav.telehealth":"Centre de télémédecine","nav.analytics":"Analytique & SLA","nav.security":"Sécurité & E2EE",
    "command.eyebrow":"PLATEFORME TEMPS RÉEL","command.title":"Centre de commande opérationnel","command.heroOverline":"CAREPOINT NEXT","command.heroTitle":"Le réseau clinique sous contrôle.","command.heroText":"Une vue opérationnelle unique sur les médecins indépendants, les prestataires non médecins, le transport médical et la demande patient.","command.platformHealth":"SANTÉ DE LA PLATEFORME","command.nominal":"Nominal","command.platformDetail":"API 99,99% · DB saine · File normale","command.visitsToday":"Visites aujourd’hui","command.activeDoctors":"Médecins actifs","command.otherProviders":"Autres prestataires","command.urgentRequests":"Demandes urgentes","command.allSpecialties":"Toutes les spécialités","command.doctorsExcluded":"Médecins explicitement exclus","command.ambulanceQueue":"File prioritaire ambulance","command.liveDemand":"DEMANDE EN DIRECT","command.visitsByModality":"Visites par modalité","command.clinicVisits":"Visites en clinique","command.telemedicine":"Télémédecine","command.homeVisits":"Visites à domicile","command.emergencyAmbulance":"Ambulance d’urgence","command.confirmed74":"74% confirmées","command.joining12":"12 rejoignent maintenant","command.enRoute9":"9 en route","command.dispatching2":"2 en dispatch","command.priorityDispatch":"Dispatch prioritaire","command.requestReceived":"Demande patient reçue","command.requestDetail":"Beyrouth · GPS vérifié · ambulance éligible en dispatch","command.elapsed":"écoulé","command.openDispatch":"Ouvrir le dispatch","command.callPatient":"Appeler le patient","command.boundaryHealth":"SANTÉ DES FRONTIÈRES","command.providerDomains":"Domaines prestataires","command.doctorDomain":"DOMAINE MÉDECINS","command.doctorBoundary":"Tous les médecins · toutes les spécialités","command.doctorBoundaryText":"Application dédiée, habilitations et hiérarchie des spécialités.","command.otherDomain":"DOMAINE AUTRES PRESTATAIRES","command.otherBoundary":"Santé + transport terrestre/aérien","command.otherBoundaryText":"Taxonomie flexible. Les médecins ne peuvent jamais y être classés.","command.patientDomain":"DOMAINE PATIENT","command.patientBoundary":"Une identité patient globale","command.patientBoundaryText":"Le consentement contrôle l’accès au contexte clinique sensible.",
    "providers.eyebrow":"TAXONOMIE FLEXIBLE · MÉDECINS EXCLUS","providers.title":"Autres prestataires indépendants","providers.domainRule":"RÈGLE DE DOMAINE","providers.ruleTitle":"Chaque prestataire non médecin est indépendant.","providers.ruleText":"Les branches de santé, l’ambulance d’urgence, le transport terrestre et aérien sont gérés ici. Les médecins sont toujours gérés dans leur domaine dédié.","providers.newCategory":"+ Nouvelle catégorie","providers.search":"Rechercher prestataires, catégories ou couverture...","providers.allStatus":"Tous les statuts","providers.allFamilies":"Toutes les familles","providers.provider":"Prestataire","providers.category":"Catégorie","providers.status":"Statut","providers.mode":"Mode / disponibilité","providers.coverage":"Couverture","providers.nonDoctorHealthcare":"SANTÉ NON MÉDECIN","providers.nonDoctorHealthcareText":"Soins infirmiers, ATS, physiothérapie, nutrition et futures catégories paramédicales.","providers.groundTransport":"TRANSPORT MÉDICAL TERRESTRE","providers.groundTransportText":"Transport patient programmé ou spécialisé par voie terrestre.","providers.airTransport":"TRANSPORT MÉDICAL AÉRIEN","providers.airTransportText":"Services d’aviation médicale avec exigences d’habilitation supplémentaires.","providers.emergencyAmbulance":"AMBULANCE D’URGENCE","providers.emergencyAmbulanceText":"Prestataires urgents éligibles au dispatch prioritaire depuis l’accueil patient.","providers.configureSchema":"Configurer le schéma →",
    "doctors.eyebrow":"DOMAINE MÉDECINS DÉDIÉ","doctors.title":"Médecins et spécialités médicales","doctors.allBranches":"TOUTES LES BRANCHES MÉDICALES","doctors.heroTitle":"Une application médecin. Toutes les spécialités.","doctors.heroText":"Chaque médecin appartient à ce domaine, de la médecine générale aux disciplines chirurgicales et diagnostiques hautement spécialisées. Aucun médecin n’appartient aux Autres Prestataires.","doctors.activeDoctors":"médecins actifs","doctors.credentialReady":"94% habilitations prêtes","doctors.credentialGovernance":"GOUVERNANCE DES HABILITATIONS","doctors.activationReadiness":"Préparation à l’activation des médecins","doctors.licenseVerified":"Licence médicale vérifiée","doctors.specialtyAssigned":"Spécialité principale attribuée","doctors.mfaEnrolled":"MFA activé",
    "appointments.eyebrow":"OPÉRATIONS MULTIMODALES","appointments.title":"Opérations unifiées des rendez-vous","appointments.clinic":"Clinique","appointments.telemedicine":"Télémédecine","appointments.homeVisit":"Visite à domicile","appointments.emergency":"Ambulance d’urgence","appointments.todayCount":"{count} aujourd’hui","appointments.separateFlow":"Flux urgent séparé","appointments.timeline":"Chronologie de prestation des soins"
  },
  es: {
    "common.today":"Hoy","common.open":"Abrir","common.filter":"Filtrar","common.verified":"Verificado","common.review":"En revisión","common.independentEntity":"Entidad independiente","common.secureSession":"SESIÓN SEGURA","common.exportSnapshot":"Exportar instantánea","common.live":"EN VIVO",
    "shell.clinicalOperations":"Operaciones Clínicas","shell.globalCommand":"Comando global...","shell.systemModules":"MÓDULOS DEL SISTEMA","shell.e2eeStatus":"ESTADO E2EE","shell.shieldPolicy":"Política de protección activa","shell.globalCareNetwork":"Red Global de Atención","shell.platformAdministrator":"Administrador de Plataforma",
    "nav.commandCenter":"Centro de Comando","nav.otherProviders":"Otros Proveedores","nav.doctors":"Médicos y Especialidades","nav.appointments":"Citas","nav.patientWorkspaces":"Espacios de Pacientes","nav.telehealth":"Centro de Telemedicina","nav.analytics":"Analítica y SLA","nav.security":"Seguridad y E2EE",
    "command.eyebrow":"PLATAFORMA EN TIEMPO REAL","command.title":"Centro de Comando de Operaciones","command.heroOverline":"CAREPOINT NEXT","command.heroTitle":"La red clínica bajo control.","command.heroText":"Una vista operativa única de médicos independientes, proveedores no médicos, transporte médico y demanda de pacientes.","command.platformHealth":"SALUD DE LA PLATAFORMA","command.nominal":"Nominal","command.platformDetail":"API 99.99% · BD saludable · Cola normal","command.visitsToday":"Visitas hoy","command.activeDoctors":"Médicos activos","command.otherProviders":"Otros proveedores","command.urgentRequests":"Solicitudes urgentes","command.allSpecialties":"Todas las especialidades","command.doctorsExcluded":"Médicos explícitamente excluidos","command.ambulanceQueue":"Cola prioritaria de ambulancias","command.liveDemand":"DEMANDA EN VIVO","command.visitsByModality":"Visitas por modalidad","command.clinicVisits":"Consultas en clínica","command.telemedicine":"Telemedicina","command.homeVisits":"Visitas domiciliarias","command.emergencyAmbulance":"Ambulancia de urgencias","command.confirmed74":"74% confirmadas","command.joining12":"12 conectándose ahora","command.enRoute9":"9 en camino","command.dispatching2":"2 en despacho","command.priorityDispatch":"Despacho prioritario","command.requestReceived":"Solicitud del paciente recibida","command.requestDetail":"Beirut · GPS verificado · despachando ambulancia elegible","command.elapsed":"transcurrido","command.openDispatch":"Abrir despacho","command.callPatient":"Llamar al paciente","command.boundaryHealth":"SALUD DE LÍMITES","command.providerDomains":"Dominios de proveedores","command.doctorDomain":"DOMINIO MÉDICOS","command.doctorBoundary":"Todos los médicos · todas las especialidades","command.doctorBoundaryText":"Aplicación dedicada, credenciales y jerarquía de especialidades.","command.otherDomain":"DOMINIO OTROS PROVEEDORES","command.otherBoundary":"Salud + transporte terrestre/aéreo","command.otherBoundaryText":"Taxonomía flexible. Los médicos nunca pueden clasificarse aquí.","command.patientDomain":"DOMINIO PACIENTE","command.patientBoundary":"Una identidad global de paciente","command.patientBoundaryText":"El consentimiento controla el acceso del proveedor al contexto clínico sensible.",
    "providers.eyebrow":"TAXONOMÍA FLEXIBLE · MÉDICOS EXCLUIDOS","providers.title":"Otros Proveedores Independientes","providers.domainRule":"REGLA DEL DOMINIO","providers.ruleTitle":"Cada proveedor no médico es independiente.","providers.ruleText":"Las ramas sanitarias, ambulancias de urgencias, transporte terrestre y transporte médico aéreo se gestionan aquí. Los médicos se gestionan siempre en el dominio dedicado de Médicos.","providers.newCategory":"+ Nueva categoría","providers.search":"Buscar proveedores, categorías o cobertura...","providers.allStatus":"Todos los estados","providers.allFamilies":"Todas las familias","providers.provider":"Proveedor","providers.category":"Categoría","providers.status":"Estado","providers.mode":"Modalidad / disponibilidad","providers.coverage":"Cobertura","providers.nonDoctorHealthcare":"SALUD NO MÉDICA","providers.nonDoctorHealthcareText":"Enfermería, ATS, fisioterapia, nutrición y futuras categorías sanitarias aliadas.","providers.groundTransport":"TRANSPORTE MÉDICO TERRESTRE","providers.groundTransportText":"Transporte de pacientes programado o especializado por tierra.","providers.airTransport":"TRANSPORTE MÉDICO AÉREO","providers.airTransportText":"Servicios de aviación médica con requisitos adicionales de credenciales.","providers.emergencyAmbulance":"AMBULANCIA DE URGENCIAS","providers.emergencyAmbulanceText":"Proveedores urgentes elegibles para despacho prioritario desde Inicio del Paciente.","providers.configureSchema":"Configurar esquema →",
    "doctors.eyebrow":"DOMINIO MÉDICOS DEDICADO","doctors.title":"Médicos y Especialidades Médicas","doctors.allBranches":"TODAS LAS RAMAS MÉDICAS","doctors.heroTitle":"Una aplicación médica. Todas las especialidades.","doctors.heroText":"Cada médico pertenece a este dominio, desde medicina general hasta disciplinas quirúrgicas y diagnósticas altamente especializadas. Ningún médico pertenece a Otros Proveedores.","doctors.activeDoctors":"médicos activos","doctors.credentialReady":"94% credenciales listas","doctors.credentialGovernance":"GOBERNANZA DE CREDENCIALES","doctors.activationReadiness":"Preparación de activación médica","doctors.licenseVerified":"Licencia médica verificada","doctors.specialtyAssigned":"Especialidad principal asignada","doctors.mfaEnrolled":"MFA activado",
    "appointments.eyebrow":"OPERACIONES MULTIMODALES","appointments.title":"Operaciones Unificadas de Citas","appointments.clinic":"Clínica","appointments.telemedicine":"Telemedicina","appointments.homeVisit":"Visita domiciliaria","appointments.emergency":"Ambulancia de urgencias","appointments.todayCount":"{count} hoy","appointments.separateFlow":"Flujo urgente separado","appointments.timeline":"Cronología de prestación de atención"
  }
} as const;

export type MessageKey = keyof typeof messages.en;
type I18nContextValue = { locale: Locale; direction: Direction; localeLabels: Record<Locale,string>; setLocale:(locale:Locale)=>void; t:(key:MessageKey, values?:Record<string,string|number>)=>string };
const I18nContext = createContext<I18nContextValue | null>(null);
const directionFor = (locale: Locale): Direction => locale === "ar" ? "rtl" : "ltr";
const interpolate = (template:string, values:Record<string,string|number>={}) => Object.entries(values).reduce((r,[k,v])=>r.replaceAll(`{${k}}`,String(v)),template);

export function LocaleProvider({ children }: { children: ReactNode }) {
  const [locale,setLocaleState] = useState<Locale>("en");
  useEffect(()=>{ const saved=window.localStorage.getItem("carepoint.locale"); if(saved && supportedLocales.includes(saved as Locale)) setLocaleState(saved as Locale); },[]);
  useEffect(()=>{ document.documentElement.lang=locale; document.documentElement.dir=directionFor(locale); window.localStorage.setItem("carepoint.locale",locale); },[locale]);
  const value = useMemo<I18nContextValue>(()=>({ locale, direction:directionFor(locale), localeLabels, setLocale:setLocaleState, t:(key,values)=>interpolate(messages[locale][key] ?? messages.en[key],values) }),[locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n(): I18nContextValue { const ctx=useContext(I18nContext); if(!ctx) throw new Error("useI18n must be used inside LocaleProvider"); return ctx; }
