import type { Locale } from "@/lib/i18n";

const text = {
  en: { patients:"Patients", patientEyebrow:"ADMINISTRATIVE PATIENT DOMAIN", patientTitle:"Patient Directory", privacy:"Administrative view only — no clinical record data is exposed here.", search:"Search name or email", status:"Status", all:"All", refresh:"Refresh", patient:"Patient", identity:"Identity", verification:"Verification", signals:"Operational signals", open:"Open record", detailTitle:"Administrative Patient Record", account:"Account & contact", dependents:"Dependents", consents:"Consents", insurance:"Insurance", incidents:"Operational / security signals", back:"Back to patients", schema:"Clinical Profile Schema", schemaEyebrow:"VERSIONED CLINICAL GOVERNANCE", schemaTitle:"Clinical Profile Schema", jurisdiction:"Jurisdiction", version:"Version", revision:"Revision", state:"State", definition:"Schema definition (JSON)", create:"Create draft", save:"Save draft", publish:"Publish", retire:"Retire", load:"Load", immutable:"Published and retired versions are immutable; historical versions are retained.", noRows:"No records found.", error:"Request failed", locked:"Locked", mfa:"MFA", activeConsent:"Active consent", coverage:"Coverage", emergency:"Emergency", transport:"Transport" },
  ar: { patients:"المرضى", patientEyebrow:"النطاق الإداري للمريض", patientTitle:"دليل المرضى", privacy:"عرض إداري فقط — لا يتم عرض أي بيانات من السجل السريري هنا.", search:"البحث بالاسم أو البريد", status:"الحالة", all:"الكل", refresh:"تحديث", patient:"المريض", identity:"الهوية", verification:"التحقق", signals:"إشارات تشغيلية", open:"فتح السجل", detailTitle:"السجل الإداري للمريض", account:"الحساب وبيانات الاتصال", dependents:"المعالون", consents:"الموافقات", insurance:"التأمين", incidents:"إشارات التشغيل / الأمان", back:"العودة للمرضى", schema:"مخطط الملف السريري", schemaEyebrow:"حوكمة سريرية بإصدارات", schemaTitle:"مخطط الملف السريري", jurisdiction:"الاختصاص", version:"الإصدار", revision:"المراجعة", state:"الحالة", definition:"تعريف المخطط (JSON)", create:"إنشاء مسودة", save:"حفظ المسودة", publish:"نشر", retire:"إيقاف", load:"تحميل", immutable:"الإصدارات المنشورة والمتوقفة غير قابلة للتعديل ويتم حفظ التاريخ.", noRows:"لا توجد سجلات.", error:"فشل الطلب", locked:"مقفل", mfa:"MFA", activeConsent:"موافقة فعالة", coverage:"تغطية", emergency:"طوارئ", transport:"نقل" },
  fr: { patients:"Patients", patientEyebrow:"DOMAINE ADMINISTRATIF PATIENT", patientTitle:"Répertoire des patients", privacy:"Vue administrative uniquement — aucune donnée du dossier clinique n’est exposée ici.", search:"Rechercher nom ou e-mail", status:"Statut", all:"Tous", refresh:"Actualiser", patient:"Patient", identity:"Identité", verification:"Vérification", signals:"Signaux opérationnels", open:"Ouvrir la fiche", detailTitle:"Fiche administrative patient", account:"Compte et contact", dependents:"Personnes à charge", consents:"Consentements", insurance:"Assurance", incidents:"Signaux opérationnels / sécurité", back:"Retour aux patients", schema:"Schéma du profil clinique", schemaEyebrow:"GOUVERNANCE CLINIQUE VERSIONNÉE", schemaTitle:"Schéma du profil clinique", jurisdiction:"Juridiction", version:"Version", revision:"Révision", state:"État", definition:"Définition du schéma (JSON)", create:"Créer un brouillon", save:"Enregistrer", publish:"Publier", retire:"Retirer", load:"Charger", immutable:"Les versions publiées et retirées sont immuables et l’historique est conservé.", noRows:"Aucun enregistrement.", error:"Échec de la requête", locked:"Verrouillé", mfa:"MFA", activeConsent:"Consentement actif", coverage:"Couverture", emergency:"Urgence", transport:"Transport" },
  es: { patients:"Pacientes", patientEyebrow:"DOMINIO ADMINISTRATIVO DEL PACIENTE", patientTitle:"Directorio de pacientes", privacy:"Vista exclusivamente administrativa: aquí no se exponen datos del expediente clínico.", search:"Buscar nombre o correo", status:"Estado", all:"Todos", refresh:"Actualizar", patient:"Paciente", identity:"Identidad", verification:"Verificación", signals:"Señales operativas", open:"Abrir ficha", detailTitle:"Ficha administrativa del paciente", account:"Cuenta y contacto", dependents:"Dependientes", consents:"Consentimientos", insurance:"Seguro", incidents:"Señales operativas / seguridad", back:"Volver a pacientes", schema:"Esquema de perfil clínico", schemaEyebrow:"GOBERNANZA CLÍNICA VERSIONADA", schemaTitle:"Esquema de perfil clínico", jurisdiction:"Jurisdicción", version:"Versión", revision:"Revisión", state:"Estado", definition:"Definición del esquema (JSON)", create:"Crear borrador", save:"Guardar borrador", publish:"Publicar", retire:"Retirar", load:"Cargar", immutable:"Las versiones publicadas y retiradas son inmutables y se conserva el histórico.", noRows:"No hay registros.", error:"Falló la solicitud", locked:"Bloqueado", mfa:"MFA", activeConsent:"Consentimiento activo", coverage:"Cobertura", emergency:"Emergencia", transport:"Transporte" },
} as const;

export type PatientGovernanceKey = keyof typeof text.en;
export function patientGovernanceText(locale: Locale, key: PatientGovernanceKey): string { return text[locale][key]; }
